language: rust
script:
  - cargo test --verbose --all --no-default-features && cargo test --features=jpeg70_abi && cargo test --features=jpeg80_abi && cargo test --verbose --all
matrix:
  include:
    - os: linux
      addons:
        apt:
          packages:
            - gcc
            - nasm
