[package]
name = "mozjpeg-sys"
description = "FFI bindings for MozJPEG v3.3.1.\n\nMozJPEG is automatically built and linked statically. Requires nasm and a C compiler."
categories = [ "external-ffi-bindings", "multimedia::images" ]
authors = ["Kornel <pornel@pornel.net>"]
include = ["src/**/*", "vendor/**/*", "Cargo.toml", "README.md"]
keywords = ["JPEG", "mozjpeg", "libjpeg", "static"]
readme = "README.md"
repository = "https://github.com/pornel/mozjpeg-sys.git"
homepage = "https://github.com/pornel/mozjpeg-sys"
license = "IJG"
build = "src/build.rs"
links = "jpeg"
version = "0.5.2"

[build-dependencies]

[build-dependencies.cc]
features = ["parallel"]
version = "1.0.3"

[build-dependencies.nasm-rs]
optional = true
version = "0.0.7"

[dependencies]
libc = "0.2.31"

[features]
arith_dec = []
arith_enc = []
default = ["nasm_simd"]
nasm_simd = ["nasm-rs"]
turbojpeg_api = []

[lib]
name = "mozjpeg_sys"
crate-type = ["staticlib", "cdylib", "lib"]
