[package]
name = "mozjpeg-sys"
description = "FFI bindings for mozjpeg.\n\nMozJPEG is automatically fetched from git master and linked statically. Requires autotools and nasm."
authors = ["Kornel <pornel@pornel.net>"]
keywords = ["JPEG", "mozjpeg", "libjpeg", "static"]
repository = "https://github.com/pornel/mozjpeg-sys.git"
homepage = "https://github.com/pornel/mozjpeg-sys"
license = "IJG"
build = "src/build.rs"
links = "jpeg"
version = "0.3.0"
include = ["src/**/*", "Cargo.toml", "README.md", "Makefile"]

[dependencies]
libc = "0.2.12"

[lib]
name = "mozjpeg_sys"
