[package]
name = "mozjpeg-sys"
description = "FFI bindings for MozJPEG v3.3.1.\n\nMozJPEG is automatically built and linked statically. Requires nasm and a C compiler."
categories = [ "external-ffi-bindings", "multimedia::images" ]
authors = ["Kornel <pornel@pornel.net>"]
include = ["src/**/*", "vendor/**/*", "Cargo.toml", "README.md"]
keywords = ["JPEG", "mozjpeg", "libjpeg", "static"]
readme = "README.md"
repository = "https://github.com/kornelski/mozjpeg-sys.git"
homepage = "https://github.com/kornelski/mozjpeg-sys"
license = "IJG"
build = "src/build.rs"
links = "jpeg"
version = "0.5.13"

[badges]
travis-ci = { repository = "kornelski/mozjpeg-sys" }

[build-dependencies]
dunce = "0.1.1"

[build-dependencies.cc]
features = ["parallel"]
version = "1.0.9"

[build-dependencies.nasm-rs]
optional = true
version = "0.1.3"

[[example]]
name = "reencode"
path = "examples/reencode.rs"

[dependencies]
libc = "0.2.31"

[features]
arith_dec = []
arith_enc = []
default = ["nasm_simd"]
nasm_simd = ["nasm-rs", "nasm-rs/parallel"]
turbojpeg_api = []
jpeg70_abi = ["arith_dec", "arith_enc"]
jpeg80_abi = ["jpeg70_abi"]

[lib]
name = "mozjpeg_sys"
crate-type = ["staticlib", "cdylib", "lib"]
